version: "3.9"

services:
  logistica-frontend:
    build:
      context: .
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - AUTH_KEYCLOAK_ID=${AUTH_KEYCLOAK_ID}
        - AUTH_KEYCLOAK_SECRET=${AUTH_KEYCLOAK_SECRET}
        - AUTH_KEYCLOAK_ISSUER=${AUTH_KEYCLOAK_ISSUER}
        - AUTH_KEYCLOAK_ADMIN=${AUTH_KEYCLOAK_ADMIN}
        - NEXT_PUBLIC_TARGET_URL=${NEXT_PUBLIC_TARGET_URL}
        - AUTH_SECRET=${AUTH_SECRET}
        - PUBLIC_KEY=${PUBLIC_KEY}
        - NEXT_HOSTNAME=${NEXT_HOSTNAME}
        - EXTERNAL_API_BASE_URL=${EXTERNAL_API_BASE_URL}
      dockerfile: Dockerfile
    container_name: logistica-frontend
    restart: unless-stopped
    
    # Porta interna que seu app expõe (ajuste se necessário)
    expose:
      - "3000"

    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - AUTH_KEYCLOAK_ID=${AUTH_KEYCLOAK_ID}
      - AUTH_KEYCLOAK_SECRET=${AUTH_KEYCLOAK_SECRET}
      - AUTH_KEYCLOAK_ISSUER=${AUTH_KEYCLOAK_ISSUER}
      - AUTH_KEYCLOAK_ADMIN=${AUTH_KEYCLOAK_ADMIN}
      - NEXT_PUBLIC_TARGET_URL=${NEXT_PUBLIC_TARGET_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - PUBLIC_KEY=${PUBLIC_KEY}
      - NEXT_HOSTNAME=${NEXT_HOSTNAME}
      - EXTERNAL_API_BASE_URL=${EXTERNAL_API_BASE_URL}

    labels:
      # Habilita o Traefik
      - "traefik.enable=true"

      # Router
      - "traefik.http.routers.logistica-frontend.rule=Host(`${NEXT_HOSTNAME}`)"
      - "traefik.http.routers.logistica-frontend.entrypoints=websecure"
      - "traefik.http.routers.logistica-frontend.service=logistica-frontend-service"

      # TLS
      - "traefik.http.routers.logistica-frontend.tls=true"
      - "traefik.http.routers.logistica-frontend.tls.certresolver=letsencrypt"

      # Load balancer → porta interna
      - "traefik.http.services.logistica-frontend-service.loadbalancer.server.port=3000"

    networks:
      - proxy

# Redes externas
networks:
  proxy:
    external: true